### ISSUE TITLE
Darwin Arm - Mac M1 

### ISSUE THREAD

**Issue by luctrate** [jenkins-x-plugins/jx-admin#237]
Following the setup guidelines on a new Apple M1 will currently lead to 
`jx admin log`
"ERROR: failed to install binary plugin jx-admin version 0.1.1 to /Users/steven/.jx3/plugins/bin: unable to locate binary for arm64 darwin for admin"

**Comment by ankitm123** [comment]
The issue is we have arm linux packages, but not darwin, I will update the release pipeline to see if we can create them.

**Comment by luctrate** [comment]
That would be great. Go the same for all other plugins i have tested so far, project, ui, ...
Makes jx3 unusable for non go Mac M1 Developers so far. Even if i build the plugin myself with darwin arm64 and place it in plugins/bin i get the same error.

**Comment by pshemass** [comment]
any update on that?

**Comment by luctrate** [comment]
@ankitm123 
I suspect it's because of the hard-coded go version within the make file that the darwin arm is not built by the go releaser.

Go Version and darwin arm support.
https://github.com/goreleaser/goreleaser/issues/1952

I have created a PR to check. Pls have a look
https://github.com/jenkins-x-plugins/jx-admin/pull/238

**Comment by msvticket** [comment]
Since version [0.1.2](https://github.com/jenkins-x-plugins/jx-admin/releases/tag/v0.1.2) darwin arm binaries are now built.

/close
