### ISSUE TITLE
Upgrading Golang version from 1.17 to 1.18 in jx-admin

### ISSUE THREAD

**Issue by Aju100** [jenkins-x-plugins/jx-admin#258]
Golang supports only 2 major releases: https://endoflife.date/go
Go 1.19 is expected to be out in August 2022.

Wrapping with the flow of this https://github.com/jenkins-x/jx/issues/8283

**Comment by rajatgupta24** [comment]
Seems like this https://github.com/jenkins-x-plugins/jx-admin/pull/264 updates the go version to `1.18` for **jx-admin**, so can close this issue.
