### ISSUE TITLE
create a command to completely remove a Jenkins X installation

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x-plugins/jx-admin#93]
we don't have a clean `jx admin destroy` command to remove all of the resources from gitops.

An implementation might be able to clone the cluster git repository and do something like `kubectl delete -R -f config-root`?

**Comment by hervelemeur** [comment]
As discovered and discussed on Slack, to avoid "not found" errors, delete first the namespaces, then the cluster:

```
kubectl delete -R -f config-root/namespaces
kubectl delete -R -f config-root/cluster
```

**Comment by msvticket** [comment]
I think is simple enough to issue the commands above as is also described in https://jenkins-x.io/v3/admin/uninstall/delete-jx/

So I think this issue can be closed.
